<a href="https://colab.research.google.com/github/yamini542/Machine-Learning/blob/main/Assesment_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#import necessary librabires and the data set 
#https://github.com/yamini542/Machine-Learning/blob/main/global%20air%20pollution%20dataset.csv

import pandas as pd
import numpy as np

from numpy import loadtxt
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, roc_auc_score, make_scorer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix






# New section

In [13]:
df=pd.read_csv('/global air pollution dataset.csv')
#load the dataset

# New section

In [14]:
df.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2               Italy   Priolo Gargallo         66     Moderate             1   
3              Poland         Przasnysz         34         Good             1   
4              France          Punaauia         22         Good             0   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good               39               Good              2   
3            Good               34               Good              0   
4            Good               22               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category  
0             Good               51           Moderate  
1             Good               41               Good  
2             Good               66           Moderate  
3             Good               20               Good  
4             Good                6               Good

# New section

In [15]:
#for this problem we dont need country and city removing those from the data set
df1=df.drop(['Country','City'],axis=1, inplace=False)
#here deoping the column and created a new data frame with out those columns
#set axis = 0 to remove rows and set axis =1 to remove columns

# New section

In [16]:
df1.describe()

AQI Value  CO AQI Value  Ozone AQI Value  NO2 AQI Value  \
count  23463.000000  23463.000000     23463.000000   23463.000000   
mean      72.010868      1.368367        35.193709       3.063334   
std       56.055220      1.832064        28.098723       5.254108   
min        6.000000      0.000000         0.000000       0.000000   
25%       39.000000      1.000000        21.000000       0.000000   
50%       55.000000      1.000000        31.000000       1.000000   
75%       79.000000      1.000000        40.000000       4.000000   
max      500.000000    133.000000       235.000000      91.000000   

       PM2.5 AQI Value  
count     23463.000000  
mean         68.519755  
std          54.796443  
min           0.000000  
25%          35.000000  
50%          54.000000  
75%          79.000000  
max         500.000000

# New section

In [17]:
#check in the dataset df1 if there is any null values
df1.notnull()

AQI Value  AQI Category  CO AQI Value  CO AQI Category  \
0           True          True          True             True   
1           True          True          True             True   
2           True          True          True             True   
3           True          True          True             True   
4           True          True          True             True   
...          ...           ...           ...              ...   
23458       True          True          True             True   
23459       True          True          True             True   
23460       True          True          True             True   
23461       True          True          True             True   
23462       True          True          True             True   

       Ozone AQI Value  Ozone AQI Category  NO2 AQI Value  NO2 AQI Category  \
0                 True                True           True              True   
1                 True                True           True              True   
2                 True                True           True              True   
3                 True                True           True              True   
4                 True                True           True              True   
...                ...                 ...            ...               ...   
23458             True                True           True              True   
23459             True                True           True              True   
23460             True                True           True              True   
23461             True                True           True              True   
23462             True                True           True              True   

       PM2.5 AQI Value  PM2.5 AQI Category  
0                 True                True  
1                 True                True  
2                 True                True  
3                 True                True  
4                 True                True  
...                ...                 ...  
23458             True                True  
23459             True                True  
23460             True                True  
23461             True                True  
23462             True                True  

[23463 rows x 10 columns]

Prediction of air pollution levels: You could try using supervised machine learning techniques to build a model that predicts air pollution levels
 in a particular location based on the AQI Value and AQI Category attributes. 

Problem definition:
Predict the air pollution level (AQI Value and AQI Category) in a particular location based on the CO AQI Category, Ozone AQI Value, Ozone AQI Category, NO2 AQI Value, NO2 AQI Category, PM2.5 AQI Value, and PM2.5 AQI Category attributes.


In [18]:
df.describe()
#describing the statisctice of the dataset

AQI Value  CO AQI Value  Ozone AQI Value  NO2 AQI Value  \
count  23463.000000  23463.000000     23463.000000   23463.000000   
mean      72.010868      1.368367        35.193709       3.063334   
std       56.055220      1.832064        28.098723       5.254108   
min        6.000000      0.000000         0.000000       0.000000   
25%       39.000000      1.000000        21.000000       0.000000   
50%       55.000000      1.000000        31.000000       1.000000   
75%       79.000000      1.000000        40.000000       4.000000   
max      500.000000    133.000000       235.000000      91.000000   

       PM2.5 AQI Value  
count     23463.000000  
mean         68.519755  
std          54.796443  
min           0.000000  
25%          35.000000  
50%          54.000000  
75%          79.000000  
max         500.000000

In [19]:
df.head()

Country              City  AQI Value AQI Category  CO AQI Value  \
0  Russian Federation        Praskoveya         51     Moderate             1   
1              Brazil  Presidente Dutra         41         Good             1   
2               Italy   Priolo Gargallo         66     Moderate             1   
3              Poland         Przasnysz         34         Good             1   
4              France          Punaauia         22         Good             0   

  CO AQI Category  Ozone AQI Value Ozone AQI Category  NO2 AQI Value  \
0            Good               36               Good              0   
1            Good                5               Good              1   
2            Good               39               Good              2   
3            Good               34               Good              0   
4            Good               22               Good              0   

  NO2 AQI Category  PM2.5 AQI Value PM2.5 AQI Category  
0             Good               51           Moderate  
1             Good               41               Good  
2             Good               66           Moderate  
3             Good               20               Good  
4             Good                6               Good

In [20]:
df1.dtypes

AQI Value              int64
AQI Category          object
CO AQI Value           int64
CO AQI Category       object
Ozone AQI Value        int64
Ozone AQI Category    object
NO2 AQI Value          int64
NO2 AQI Category      object
PM2.5 AQI Value        int64
PM2.5 AQI Category    object
dtype: object

In [21]:
df1['CO AQI Category'].unique()

array(['Good', 'Unhealthy for Sensitive Groups', 'Moderate'], dtype=object)

In [22]:
df1['CO AQI Value'].unique()

array([  1,   0,   3,   2,   5,   4,   7,  31,  12,  14,   9,   6,  10,
         8,  15,  27,  11,  16,  21,  13, 133,  22,  20,  28,  18,  17,
        19,  67,  51,  41,  35,  49,  36,  23])

In [23]:
df1['Ozone AQI Category'].unique()

array(['Good', 'Moderate', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy'], dtype=object)

In [24]:
df1['Ozone AQI Value'].unique()

array([ 36,   5,  39,  34,  22,  14,  35,  29,  41,  89,  68,  24, 139,
        50,  46,  30, 100,  47,   4,  71,  28,  10,  95,   0,  16,  37,
        31,  15,   9,  18,  19,  20,  32,   7,  64,  23, 162,  25,  81,
        26,  40,  17,  33,   3,  38,  11,  99, 203,  43,  82,   2,  44,
       150, 113,  13,  42,  48,   8, 168,  27,  12, 167,  92,  61,   6,
       155, 138, 109,  45,  53,  69,  49,  65, 125,  52,  66,  21, 198,
       107,   1, 117,  57, 170, 119,  90, 179,  60, 111, 152,  62, 133,
        98, 145, 136, 159, 153,  91,  51, 192, 172,  73, 207,  59, 169,
        74, 130,  78,  54, 116, 124,  79, 135, 201,  75, 178, 134, 164,
       108,  55, 190, 123, 176, 151, 206, 106, 157, 183, 163, 110, 102,
        84, 103, 129,  56,  63,  72, 146,  70, 148, 200,  85, 144,  58,
        86, 142,  88, 154, 140, 137,  76,  87, 180,  67,  83, 166, 188,
       156, 177, 115, 173, 143, 182,  80, 191, 160, 181, 171,  77, 101,
       141,  97, 165, 202,  96, 147, 118, 161, 131, 187, 121, 20

In [25]:
df1['NO2 AQI Category'].unique()

array(['Good', 'Moderate'], dtype=object)

In [26]:
df1['NO2 AQI Value'].unique()

array([ 0,  1,  2, 11,  3,  7,  9,  6,  4, 23, 13, 15,  5,  8, 24, 20, 10,
       19, 36, 22, 16, 21, 12, 18, 25, 26, 14, 27, 17, 37, 28, 33, 31, 52,
       44, 91, 30, 34, 29, 38, 47, 59, 40, 35, 69, 42, 39, 51, 53, 49, 41,
       32, 46, 61, 48, 63, 58, 64, 43])

In [27]:
df1['PM2.5 AQI Category'].unique()

array(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], dtype=object)

In [28]:
df1['PM2.5 AQI Value'].unique()

array([ 51,  41,  66,  20,   6,  54,  62,  64, 142,  58, 158,  83,  59,
       154,  55,  72, 161,  28, 118,  33, 150,  81,  67,  17,  56,  77,
        44,  30,  15,  79,  34,  61,  32,  25, 247,  45,  36, 124, 157,
        60, 153,  22,  47,  37,  89,  52,  13,  88,  42, 189,  49, 151,
        35,  90,  48,  73, 170, 155,  46, 172,  38, 105,  21,  29, 166,
        27,  23,  31, 156, 133,   7,  50,  65,  53,  57, 107,  80, 163,
       126,  63,  86,  78, 112, 121, 160, 144,  69,  84,  10,  75,  99,
        98, 103, 307, 102, 115,  40, 127,  82,  92,  43, 143, 187, 188,
       139, 145,  76, 104,  19,  39,  97, 194,  26,  70, 466, 380, 222,
       182,  68, 171,  91,  71,  11,  16, 152,  93,  24, 132, 202, 167,
        18,  94, 101,  74, 391,  12, 208, 122, 260, 193, 284, 191, 226,
        14, 464,  95, 190, 292, 173, 198, 175, 500, 169, 120, 129, 100,
       176, 164, 117, 119, 180, 362, 184, 443,   5, 125, 376, 108, 230,
         9, 335, 159, 493, 174, 162, 130, 478, 146,   3, 106, 14

In [29]:
df1['AQI Category'].unique()

array(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], dtype=object)

In [30]:
df1['AQI Value'].unique()

array([ 51,  41,  66,  34,  22,  54,  62,  64, 142,  68, 158,  83,  59,
       154,  55,  72, 161,  28, 118,  33, 150,  81,  67,  31,  56,  77,
        44,  30,  79,  61,  32,  29, 247,  45,  36, 124, 157,  60, 153,
        47,  37,  58,  89,  52,  38,  88,  42, 189,  49, 203,  35,  90,
        48,  19,  73, 170, 155,  46, 172,  21, 166,  27,  23, 168,  40,
       133,  50,  25,  65,  53,  57, 167,  80, 163, 126,  63,  86,  78,
       112, 121, 160, 144,  69,  84,  20,  75,  98, 103, 307, 151, 102,
       115,  17, 127, 125,  92, 143, 187, 156, 105, 198, 139, 145,  13,
        26, 107,  76, 104,  39,  97, 194,  70, 500, 380, 222, 117, 182,
       171,  91,  71,  24, 152,  93, 132, 179, 202,  94, 101,  74, 444,
        18, 208, 122, 303, 193, 356, 191, 226,  16,  43,  95, 190, 292,
       173,   6, 175, 169, 120,  12, 129, 192, 100, 176, 164, 119, 180,
       434, 184, 207, 138, 108, 230, 390, 159, 116, 174, 162, 130, 135,
       201,  14, 178, 106, 140, 334, 195, 197, 409, 186, 185,  1

In [36]:
#lets find out if thre is any missing data if there is replce with null value or 0
len(df1.loc[df1['AQI_Value']==' ']),
len(df1.loc[df1['AQI_Category']==' '])
len(df1.loc[df1['CO_AQI_Category']==' '])
len(df1.loc[df1['CO_AQI_Value']==' '])
len(df1.loc[df1['NO2_AQI_Value']==' '])
len(df1.loc[df1['NO2_AQI_Category']==' '])
len(df1.loc[df1['Ozone_AQI_Category']==' '])
len(df1.loc[df1['Ozone_AQI_Value']==' '])

len(df1.loc[df1['PM2.5_AQI_Category']==' '])
len(df1.loc[df1['PM2.5_AQI_Value']==' '])







0

there is no missing data in the dataframe (d1)

In [34]:
df1.columns = df1.columns.str.replace(' ', '_')


In [37]:
df1.columns

Index(['AQI_Value', 'AQI_Category', 'CO_AQI_Value', 'CO_AQI_Category',
       'Ozone_AQI_Value', 'Ozone_AQI_Category', 'NO2_AQI_Value',
       'NO2_AQI_Category', 'PM2.5_AQI_Value', 'PM2.5_AQI_Category'],
      dtype='object')

In [38]:
df1['AQI_Category'] = df1['AQI_Category'].replace(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], ['2','1','3','4','5','6'])
#replacing the values with a number 
df1['CO_AQI_Category'] = df1['CO_AQI_Category'].replace(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], ['2','1','3','4','5','6'])
df1['NO2_AQI_Category'] = df1['NO2_AQI_Category'].replace(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], ['2','1','3','4','5','6'])
df1['Ozone_AQI_Category'] = df1['Ozone_AQI_Category'].replace(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], ['2','1','3','4','5','6'])
df1['PM2.5_AQI_Category'] = df1['PM2.5_AQI_Category'].replace(['Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy',
       'Very Unhealthy', 'Hazardous'], ['2','1','3','4','5','6'])


###category columns are object data type in XGBoost it only allows int,float or boolean data type since, I am converting the object value in to numeric()

values are like 'Moderate', 'Good', 'Unhealthy for Sensitive Groups', 'Unhealthy','Very Unhealthy', 'Hazardous'

replacing these values with 
Good(1)
MOderate(2)
Unhealhty for sensitive groups(3)
Unhealthy(4)
very unhealthy(5)
Hazordous(6)

In [39]:
df1.head()

AQI_Value AQI_Category  CO_AQI_Value CO_AQI_Category  Ozone_AQI_Value  \
0         51            2             1               1               36   
1         41            1             1               1                5   
2         66            2             1               1               39   
3         34            1             1               1               34   
4         22            1             0               1               22   

  Ozone_AQI_Category  NO2_AQI_Value NO2_AQI_Category  PM2.5_AQI_Value  \
0                  1              0                1               51   
1                  1              1                1               41   
2                  1              2                1               66   
3                  1              0                1               20   
4                  1              0                1                6   

  PM2.5_AQI_Category  
0                  2  
1                  1  
2                  2  
3                  1  
4                  1